### PR TITLE
First swing at a Parser and Builder for a JWT replacement.

### PR DESCRIPTION
**Pull request by paragonie-scott**
See #3 

(The Travis CI failures are not occurring locally, but I'm not going to squash the commits to hide the fact that they exist.)

### CODE REVIEW

**Comment by paragonie-scott** [comment]
The tests may be passing, but I am not 100% happy with the API. Rather than let it fester on a hard drive somewhere until I get around to it, I thought I'd get a PR open for it.

**Comment by carnage** [comment]
I'll give it a look over in the morning if you wish?

**Comment by paragonie-scott** [comment]
This will probably take a day or two before I'm happy enough with it to merge.

**Comment by paragonie-scott** [comment]
There, I feel better about the current state of affairs than I did yesterday. I got rid of the redundant `Builder` class. I'm keeping the Parser separate, and might add support for validation constraints (e.g. "must be non-expired").

**Comment by paragonie-scott** [comment]
Okay @carnage if you have time to review this, I'd greatly appreciate it. I know documentation/comments are a big lacking, but that's something I intend to do in one fell swoop before v0.2.0 is tagged.

**Comment by carnage** [comment]
You were too quick for me to finish reviewing; but I was planning to send a PR with some suggestions anyway so I'll just Pr against master instead

**Pull request merged**
